### ISSUE TITLE
LUKS version

### ISSUE THREAD

**Issue by PowerPress** [BusKill/veracrypt-self-destruct#1]
Any change you could create a LUKS version of this for linux users who use LUKS instead of Veracrypt? It would be awesome to be able to wipe the LUKS header as well.

**Comment by maltfield** [comment]
@PowerPress This actually is already done :) iirc it finishes the wipe and is off in less than 6 seconds.

 * https://github.com/BusKill/buskill-linux/blob/master/triggers/buskill-selfdestruct.sh

I'm currently working on a detailed write-up about this script (including some pretty detailed forensic analysis) and how to use it, which will be posted on our blog when finished:

 * https://www.buskill.in/blog/

For updates, subscribe to RSS or our email mailing list:

 * https://www.buskill.in/#newsletter
